fixed google-code Issue 1: TypeError: mark_install() got an unexpected keyword argument 'autoFix'
There was an issue with the original code that was reported on Google Code.
The author of the code provided a solution in his answer, but didn't update
the code accordingly.

Source: http://code.google.com/p/apt-downgrade/issues/detail?id=1

 Reported by naught...@gmail.com, Nov 12, 2013

What steps will reproduce the problem?
1. run the code
2. press yes to a downgrade choice
3. error

What is the expected output? What do you see instead?
Expect package to be downgraded, instead I get:

Force 'ladish' version
  from 1:1+git20121120-1+pylash2~raring1
  to   1+dfsg0-4 (saucy) [y]? y
Traceback (most recent call last):
  File "./apt-downgrade.py", line 77, in <module>
    pkg.mark_install(autoFix=False, fromUser=False)
TypeError: mark_install() got an unexpected keyword argument 'autoFix'

---


Jan 12, 2014
#1 directr...@gmail.com

in the file, replace autoFix with auto_fix and fromUser with from_user. Then change cache.commit to just be cache.commit(). That's how I got it to work.

---

Jan 12, 2014
#2 directr...@gmail.com

And when I say change cache.commit, I mean replace the entire cache.commit call with that empty call.